# https://www.playframework.com/documentation/latest/Configuration

db.default.driver=com.mysql.cj.jdbc.Driver
db.default.url="jdbc:mysql://localhost:3308/be_scala_crud"
db.default.username="root"
db.default.password="root123"